import typeBuilder from '../helper'

export default typeBuilder([
  'ADS_START_REQUESTED',

  'IMA_WAIT_SDK_STARTED',
  'IMA_WAIT_SDK_ENDED',
  'IMA_INIT_STARTED',
  'IMA_INIT_ENDED',
  'IMA_INIT_ADS_LOADER_STARTED',
  'IMA_INIT_ADS_LOADER_ENDED',
  'IMA_ADS_MANAGER_CHANGED',
  'IMA_REQUEST_ADS_STARTED',
  'IMA_REQUEST_ADS_ENDED',
  'IMA_START_ADS_REQUESTED',
  'IMA_START_ADS_STARTED',
  'IMA_START_ADS_ENDED',

  'CONTENT_PAUSE_REQUESTED',
  'CONTENT_RESUME_REQUESTED',

  'AD_SLOT_STARTED',
  'AD_SLOT_COMPLETED',
  'AD_SLOT_SUMMARY',

  'AD_LOADED',
  'AD_BUFFERING',
  'AD_STARTED',
  'AD_PROGRESS',
  'AD_FIRST_QUARTILE',
  'AD_MIDPOINT',
  'AD_THIRD_QUARTILE',
  'AD_COMPLETED',
  'AD_CLICKED',
  'AD_PAUSED',
  'AD_RESUMED',
  'AD_SKIPPED',
  'AD_BREAK_DISCARDED',
  'AD_ERROR',

  'ALL_ADS_COMPLETED',

  'OVERLAY_ENDED',

  'HEADER_BIDDING_FETCH_STARTED',
  'HEADER_BIDDING_FETCH_ENDED'
])
