import typeBuilder from '../helper'

export default typeBuilder([
  'CONTENT_BUFFERING',
  'CONTENT_ENDED',
  'CONTENT_ERROR_FATAL',
  'CONTENT_ERROR',
  'CONTENT_GEOBLOCKED',
  'CONTENT_LOAD_START',
  'CONTENT_MUTED_CHANGED',
  'CONTENT_PAUSED',
  'CONTENT_PLAY',
  'CONTENT_PLAYING',
  'CONTENT_PROGRAM_CHANGE_FAKE',
  'CONTENT_PROGRAM_CHANGE',
  'CONTENT_SEEKED',
  'CONTENT_SEEKING',
  'CONTENT_START_REQUESTED',
  'CONTENT_STOPPED',
  'CONTENT_TIME_UPDATED',
  'CONTENT_VOLUME_CHANGED',
  'CONTENT_WAITING',
  'PLAY_FALLBACK_STREAM',
  'PLAY_NEXT_VIDEO',
  'PLAYBACK_ENDED'
])
