export default {
  CAN_PLAY: 'canplay',
  CAN_PLAY_THROUGH: 'canplaythrough',
  DURATION_CHANGE: 'durationchange',
  ENDED: 'ended',
  ERROR: 'error',
  LOAD_START: 'loadstart',
  LOADED_METADATA: 'loadedmetadata',
  PAUSE: 'pause',
  PLAY: 'play',
  PLAYING: 'playing',
  PROGRESS: 'progress',
  SEEKED: 'seeked',
  SEEKING: 'seeking',
  STOPPED: 'stopped',
  SUSPEND: 'suspend',
  TIME_UPDATE: 'timeupdate',
  VOLUME_CHANGE: 'volumechange',
  WAITING: 'waiting'
}
